---
name: deploy-orion-insight

on:[push]
  # workflow_dispatch:
  # push:
  #   branches:
  #     - deploy

# these are the jobs
jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Make
        run: sudo apt install make -y
      - name: Install Application Requirements
        run: make requirements
      - name: Install Test Utilities
        run: make dev-setup
      - name: Run All Checks
        run: make run-checks

  # deployment:
  #   name: deployment
  #   runs-on: ubuntu-latest
  #   needs: run-tests
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3
  #     - name: Install Terraform
  #       uses: hashicorp/setup-terraform@v2
  #     - name: Configure Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #     - name: Terraform Init
  #       run: terraform init
  #       working-directory: ./terraform
  #     - name: Terraform Plan
  #       id: plan
  #       run: terraform plan
  #       working-directory: ./terraform
  #     - name: Terraform Plan Status
  #       if: steps.plan.outcome == 'failure'
  #       run: exit 1
  #       working-directory: ./terraform
  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve
  #       working-directory: ./terraform
